# Generated by Django 5.1.15 on 2026-09-01 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Filamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('material', models.CharField(max_length=100, verbose_name='Material')),
                ('cor', models.CharField(max_length=100, verbose_name='Cor')),
                ('peso_inicial', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Peso Inicial (g)')),
                ('peso_atual', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Peso Atual (g)')),
                ('custo_rolo', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Custo do Rolo')),
                ('data_entrada', models.DateField(auto_now_add=True, verbose_name='Data de Entrada')),
                ('fornecedor', models.CharField(blank=True, max_length=150, null=True, verbose_name='Fornecedor')),
                ('codigo_lote', models.CharField(blank=True, max_length=100, null=True, verbose_name='Código/Lote')),
                ('localizacao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Localização')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Filamento',
                'verbose_name_plural': 'Filamentos',
                'ordering': ['-data_entrada'],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('consumo', 'Consumo (Produção)'), ('perda', 'Perda'), ('ajuste', 'Ajuste Manual')], max_length=20, verbose_name='Tipo de Movimentação')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora')),
                ('quantidade', models.DecimalField(decimal_places=2, help_text='Valores positivos para entrada, negativos para saída', max_digits=8, verbose_name='Quantidade (g)')),
                ('quantidade_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Quantidade Anterior (g)')),
                ('quantidade_nova', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Quantidade Nova (g)')),
                ('motivo', models.TextField(blank=True, null=True, verbose_name='Motivo / Observação')),
                ('filamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='estoque.filamento')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'ordering': ['-data'],
            },
        ),
    ]
