# Generated by Django 5.1.15 on 2026-09-13 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filamento',
            options={'ordering': ['-data_entrada'], 'verbose_name': 'Item de Estoque', 'verbose_name_plural': 'Itens de Estoque'},
        ),
        migrations.AddField(
            model_name='filamento',
            name='nome',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='filamento',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Preço (R$)'),
        ),
        migrations.AddField(
            model_name='filamento',
            name='quantidade',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='filamento',
            name='cor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cor'),
        ),
        migrations.AlterField(
            model_name='filamento',
            name='custo_rolo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Custo do Rolo'),
        ),
        migrations.AlterField(
            model_name='filamento',
            name='marca',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='filamento',
            name='material',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Material'),
        ),
        migrations.AlterField(
            model_name='filamento',
            name='peso_atual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Peso Atual (g)'),
        ),
        migrations.AlterField(
            model_name='filamento',
            name='peso_inicial',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Peso Inicial (g)'),
        ),
    ]
