# Generated by Django 5.1.15 on 2026-09-01 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Categoria')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Categoria de Produto',
                'verbose_name_plural': 'Categorias de Produtos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('codigo', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='produtos/', verbose_name='Foto')),
                ('material', models.CharField(blank=True, max_length=100, null=True, verbose_name='Material Recomendado')),
                ('cor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cor Recomendada')),
                ('peso_estimado', models.DecimalField(decimal_places=2, help_text='Peso estimado em gramas', max_digits=8, verbose_name='Peso Estimado (g)')),
                ('tempo_estimado', models.DurationField(blank=True, help_text='Formato: HH:MM:SS', null=True, verbose_name='Tempo Estimado de Impressão')),
                ('custo_estimado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Custo Estimado')),
                ('preco_venda', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço de Venda')),
                ('margem_lucro', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Margem de Lucro (%)')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='produtos.categoriaproduto')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['nome'],
            },
        ),
    ]
