# Generated by Django 5.1.15 on 2026-09-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='cor',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='observacoes',
        ),
        migrations.AddField(
            model_name='produto',
            name='custo_embalagem',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Custo de Embalagem (R$)'),
        ),
        migrations.AddField(
            model_name='produto',
            name='custo_insumos',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Custo de Insumos (R$)'),
        ),
        migrations.AddField(
            model_name='produto',
            name='custo_kwh_energia',
            field=models.DecimalField(decimal_places=2, default=0.85, max_digits=8, verbose_name='Tarifa de Energia (R$/kWh)'),
        ),
        migrations.AddField(
            model_name='produto',
            name='custo_mao_de_obra',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Custo de Mão de Obra (R$)'),
        ),
        migrations.AddField(
            model_name='produto',
            name='custo_taxas_marketplace',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Taxas do Marketplace (R$)'),
        ),
        migrations.AddField(
            model_name='produto',
            name='marketplace',
            field=models.CharField(default='direto', help_text='Venda Direta, Shopee, TikTok Shop', max_length=50, verbose_name='Marketplace Padrão'),
        ),
        migrations.AddField(
            model_name='produto',
            name='potencia_impressora_w',
            field=models.DecimalField(decimal_places=2, default=150.0, max_digits=8, verbose_name='Potência da Impressora (W)'),
        ),
        migrations.AddField(
            model_name='produto',
            name='valor_kg_filamento',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço do Filamento (R$/kg)'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='codigo',
            field=models.CharField(blank=True, help_text='Código SKU único interno', max_length=50, null=True, unique=True, verbose_name='Código / SKU'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='custo_estimado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Custo Total de Produção (R$)'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição e Especificações'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/', verbose_name='Foto do Produto'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='margem_lucro',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Margem de Lucro (%)'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='material',
            field=models.CharField(blank=True, help_text='Ex: PLA, PETG, ABS, Resina', max_length=100, null=True, verbose_name='Material (Filamento)'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Nome do Produto'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='peso_estimado',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Peso em gramas (g)', max_digits=8, verbose_name='Peso Estimado (g)'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_venda',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço de Venda (R$)'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='tempo_estimado',
            field=models.DurationField(blank=True, help_text='Duração (HH:MM:SS)', null=True, verbose_name='Tempo de Impressão'),
        ),
        migrations.DeleteModel(
            name='CategoriaProduto',
        ),
    ]
