# Generated by Django 5.1.15 on 2026-09-01 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Impressora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('fabricante', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fabricante')),
                ('modelo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo')),
                ('numero_identificacao', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Identificação')),
                ('data_aquisicao', models.DateField(blank=True, null=True, verbose_name='Data de Aquisição')),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('imprimindo', 'Imprimindo'), ('manutencao', 'Em Manutenção'), ('inativa', 'Inativa')], default='disponivel', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Impressora',
                'verbose_name_plural': 'Impressoras',
                'ordering': ['nome'],
            },
        ),
    ]
