# Generated by Django 5.1.15 on 2026-09-13 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impressoras', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impressora',
            name='numero_identificacao',
        ),
        migrations.RemoveField(
            model_name='impressora',
            name='status',
        ),
        migrations.AddField(
            model_name='impressora',
            name='potencia_w',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Potência consumida pela impressora em Watts (W)', max_digits=8, null=True, verbose_name='Potência (W)'),
        ),
    ]
