# Generated by Django 5.1.15 on 2026-09-01 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentacaoFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=10, verbose_name='Tipo')),
                ('categoria', models.CharField(choices=[('vendas', 'Vendas'), ('pedidos', 'Pedidos'), ('outros_recebimentos', 'Outros Recebimentos'), ('filamento', 'Filamento'), ('energia', 'Energia'), ('embalagens', 'Embalagens'), ('frete', 'Frete'), ('taxas', 'Taxas'), ('manutencao', 'Manutenção'), ('outros_custos', 'Outros Custos')], max_length=30, verbose_name='Categoria')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('data', models.DateField(verbose_name='Data')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_financeiras', to='pedidos.pedido')),
            ],
            options={
                'verbose_name': 'Movimentação Financeira',
                'verbose_name_plural': 'Movimentações Financeiras',
                'ordering': ['-data', '-data_registro'],
            },
        ),
    ]
