# Generated by Django 5.1.15 on 2026-09-01 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estoque', '0001_initial'),
        ('impressoras', '0001_initial'),
        ('pedidos', '0001_initial'),
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Quantidade Perdida (g)')),
                ('motivo', models.CharField(choices=[('soltou_mesa', 'Peça soltou da mesa'), ('falha_impressao', 'Falha de impressão'), ('erro_fatiamento', 'Erro de fatiamento'), ('erro_configuracao', 'Erro de configuração'), ('bico_entupido', 'Bico entupido'), ('problema_impressora', 'Problema na impressora'), ('teste', 'Teste'), ('outro', 'Outro')], max_length=50, verbose_name='Motivo')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('filamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.filamento')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedidos.pedido')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Perda',
                'verbose_name_plural': 'Perdas',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Producao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('cor', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cor')),
                ('peso_previsto', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Peso Previsto (g)')),
                ('tempo_previsto', models.DurationField(blank=True, null=True, verbose_name='Tempo Previsto')),
                ('data_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Data de Início')),
                ('data_conclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('status', models.CharField(choices=[('aguardando', 'Aguardando'), ('imprimindo', 'Imprimindo'), ('concluido', 'Concluído'), ('falhou', 'Falhou'), ('cancelado', 'Cancelado')], default='aguardando', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('filamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producoes', to='estoque.filamento')),
                ('impressora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producoes', to='impressoras.impressora')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producoes', to='pedidos.pedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producoes', to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Produção',
                'verbose_name_plural': 'Produções',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='RegistroImpressao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_utilizado', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Peso Utilizado (g)')),
                ('tempo_impressao', models.DurationField(verbose_name='Tempo de Impressão')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('resultado', models.CharField(choices=[('sucesso', 'Sucesso'), ('falha', 'Falha')], max_length=20, verbose_name='Resultado')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('filamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.filamento')),
                ('impressora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='impressoras.impressora')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pedidos.pedido')),
                ('producao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impressoes', to='producao.producao')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Registro de Impressão',
                'verbose_name_plural': 'Registros de Impressões',
                'ordering': ['-data'],
            },
        ),
    ]
